CREATE TABLE passenger (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    orderer VARCHAR(50) NOT NULL,
    number_of_persons INTEGER NOT NULL
);

CREATE TABLE cargo (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    pickup_place VARCHAR(50) NOT NULL,
    weight INTEGER NOT NULL
);


ALTER TABLE vehicle_usage
ADD passenger_id INTEGER DEFAULT NULL;
ALTER TABLE vehicle_usage
ADD CONSTRAINT FOREIGN KEY (passenger_id) REFERENCES passenger(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE vehicle_usage
ADD cargo_id INTEGER DEFAULT NULL;
ALTER TABLE vehicle_usage
ADD CONSTRAINT FOREIGN KEY (cargo_id) REFERENCES cargo(id) ON UPDATE CASCADE ON DELETE CASCADE;